name: CI + CD 2.0

on: 
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      -name: Testing
       run: echo Is this working?



