name: CI + CD

on:
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: echo The infrastructure has been built!
        
  Test: 
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v2
      
      - name: Test
        run: echo The test passed!
    
  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request'
    needs: [Build, Test]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy to Development
        run: echo ${{ github.event.number }}
    
  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/Staging'
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Delpoy to Staging
        run: echo I am being staged!
        
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy to Staging
        run: echo I am ready for production! 
