name: CI + CD 2.0

on:
  pull_request:
    branches:
      - Development
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Is this working?
