name: CI + CD

on:
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: echo The infrastructure has been built!
        
  Test: 
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo ${{ github.event.pull_request.base.ref }}
    
  DeployDev:
    name: Deploy to Dev 
    if: github.event.pull_request.base.ref == 'Development'
    needs: [Build, Test]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy to Development
        run: echo ${{ github.event.number }}
      - name: Create Pull Request
        uses: actions/github-script@v6.1.0
        with: 
          script: |
            github.createPullRequest({
             owner: context.payload.repository.owner.login,
             repo: context.payload.repository.name,
             title: github.event.pull_request.name
             base: "Staging",
             head: "Development"
            })
          github-token: ${{ github.token }}
        
    
  DeployStaging:
    name: Deploy to Staging 
    if: github.event.pull_request.base.ref == 'Staging'
    needs: [Build, Test]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Delpoy to Staging
        run: echo I am being staged!
        
            
  DeployProd:
    name: Deploy to Production 
    if: github.event.pull_request.base.ref == 'main'
    needs: [Build, Test]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy to Staging
        run: echo I am ready for production! 
